### ISSUE TITLE
Is there any plan to add the function of recording ecg waveform?

### ISSUE THREAD

**Issue by fixernhc** [JanCBrammer/OpenHRV#20]

**Comment by JanCBrammer** [comment]
Thanks for your question @fixernhc. Currently, I have no concrete plan to implement this feature, since it's not immediately relevant to the biofeedback. What's your usecase?
Here's someone who wrote a script to acquire ECG data from the H10: https://github.com/kylehovey/polar-h10-ecg/blob/main/index.py.

**Comment by fixernhc** [comment]
> Thanks for your question @fixernhc. Currently, I have no concrete plan to implement this feature, since it's not immediately relevant to the biofeedback. What's your usecase? Here's someone who wrote a script to acquire ECG data from the H10: https://github.com/kylehovey/polar-h10-ecg/blob/main/index.py.

Thanks for your reply which helps me a lot.

**Comment by JanCBrammer** [comment]
Good to hear! I'm closing the issue for now.
