### ISSUE TITLE
Recording function doesn't work on Windows

### ISSUE THREAD

**Issue by MikkelVissingR** [JanCBrammer/OpenHRV#4]
Amazing programme - the perfect application for a project I'm working on! Unfortunately, the recording function doesn't work in the Windows program, giving the error message: "Couldn't start recording host localhost, port 6379. 

Any why this happens or what I could try to fix it?

I tried to get the Python version up and running on my Mac as well, but it seems there are some issues and overlaps between the QT modules that keeps it from starting up properly.

**Comment by JanCBrammer** [comment]
Hi @MikkelVissingR, thanks for getting in touch. 

The recording functionality currently requires access to a running Redis database on the machine that runs OpenHRV (hence `localhost, port 6379`). This is due to the fact that OpenHRV was used on a project where we recorded HRV and biofeedback alongside data coming from another machine that ran a virtual reality application. The virtual reality machine sent its data to Redis. 

I meant to make the recording independent of Redis for a while now but haven't gotten around to it yet. In the meantime you could spin up a Redis server on the machine that runs OpenHRV. This is a hack of course but should enable you to record your data.

Let me know if you have any more questions.

**Comment by MikkelVissingR** [comment]
Awesome, thanks a lot for the response - it worked perfectly!

**Comment by JanCBrammer** [comment]
Nice. Good luck with the project!
