### ISSUE TITLE
new python 3.12.1 not compatible?

### ISSUE THREAD

**Issue by kalleick** [JanCBrammer/OpenHRV#40]
Hi,
when i try to install with:
pip install git+https://github.com/JanCBrammer/OpenHRV.git
i get this error:
ERROR: Package 'openhrv' requires a different Python: 3.12.1 not in '==3.11.*'

can you upgrade your code or do you have a hint, what to do?

thx
Patrick

**Comment by JanCBrammer** [comment]
Thanks for your question @kalleick.
I've pinned the Python version to 3.11 (as well as the PySide6 version) for now to ensure compatibility and narrow down the problem space regarding Bluetooth issues.

If you're working with a local copy of the repository you could just relax the Python version yourself by changing 
https://github.com/JanCBrammer/OpenHRV/blob/211d4cef05ebbfb2fcccc906e91ee29077640aff/pyproject.toml#L4

Otherwise, you could try installing Python 3.11 (e.g., using https://github.com/pyenv/pyenv).

**Comment by Maltimore** [comment]
I've done this today (relaxing the python version requirement) and can confirm that it works perfectly with python 3.9.2. It seems very likely then that it would work at least with python between (inclusive) 3.9 and 3.11. Maybe at some point you could consider relaxing the constraints in the official `pyproject.toml`, as it may help others who are not confident to change the source code.
