### ISSUE TITLE
Improve bluetooth connection speed

### ISSUE THREAD

**Issue by schlamar** [JanCBrammer/OpenHRV#6]
The bleak bluetooth backend on Windows is doing a (second) bluetooth scan if you are passing an address to BleakClient. If you pass the already discovered device by the scan, the connection speed can be significantly improved:

I did this quick and dirty in model.py:

    @Slot(object)
    def set_addresses(self, value):
        addresses = list()
        self.devices = dict()
        for v in value:
            self.devices[v.address] = v
            addresses.append(f"{v.name}, {v.address}")
        self._addresses = addresses
        self.addresses_update.emit(("SensorAddresses", self._addresses))

and view.py:

    def connect_sensor(self):
        if not self.address_menu.currentText():
            return
        address = self.address_menu.currentText().split(",")[1].strip()    # discard device name
        if address not in self.model.devices:
            print(f"Invalid sensor address: {address}.")
            return
        device = self.model.devices[address]
        asyncio.run_coroutine_threadsafe(self.sensor.connect_client(device),
                                         self.sensor.loop)

I'm not sure how you would better structure this in your MVC pattern.

**Comment by JanCBrammer** [comment]
> The bleak bluetooth backend on Windows is doing a (second) bluetooth scan if you are passing an address to BleakClient.

Thanks for spotting this! In general, I'm not super happy with the Bluetooth situation. The fact that bleak is asynchronous clutters the sensor code unnecessarily: the sensor is running in its own thread anyway and not much else is happening in the sensor thread, which makes the point of the async implementation somewhat mute. I'm using bleak since from what I've seen, its the best Bluetooth solution for Python by quite some margin. PySide6 quite recently released their own Bluetooth API, I'm curious if that could replace bleak (see #7).

**Comment by schlamar** [comment]
You should have a look at https://pypi.org/project/qasync/

This should make everything much easier as coroutines can be used in main thread.

**Comment by JanCBrammer** [comment]
> You should have a look at https://pypi.org/project/qasync/

Didn't know that one. Will check it out when the experiment with #7 fails.

**Comment by JanCBrammer** [comment]
Closing with #13.
